insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (1, 'Heller LLC', 789, 'SHOP', 1);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (2, 'Barrows, Kassulke and Schumm', 507, 'SHOP', 2);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (3, 'Gusikowski LLC', 615, 'SMALL_SHOP', 3);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (4, 'Zieme, Willms and Skiles', 857, 'SHOP7', 4);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (5, 'Nienow, Johnston and Sauer', 458, 'SHOP', 5);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (6, 'Satterfield LLC', 518, 'SHOP', 6);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (7, 'Schaden and Sons', 578, 'SHOP', 7);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (8, 'Raynor and Sons', 430, 'SHOP', 8);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (9, 'Stiedemann-Beatty', 572, 'SHOP', 9);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (10, 'Graham-Mitchell', 686, 'SHOP', 10);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (11, 'Osinski, Beier and Treutel', 277, 'SHOP', 11);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (12, 'Bergstrom-Jaskolski', 161, 'SMALL_SHOP', 12);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (13, 'Simonis-Block', 330, 'SMALL_SHOP', 13);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (14, 'Hartmann, Kulas and Becker', 846, 'SMALL_SHOP', 14);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (15, 'Harber Inc', 382, 'SMALL_SHOP', 15);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (16, 'Veum and Sons', 868, 'SHOP', 16);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (17, 'Donnelly Group', 410, 'SMALL_SHOP', 17);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (18, 'Koepp, Keeling and Bayer', 255, 'SMALL_SHOP', 18);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (19, 'Jacobi Inc', 274, 'SHOP', 19);
insert into SIDLO (id_sidla, jmeno, plocha, typ_sidla, adresa) values (20, 'Conn-Gorczany', 213, 'SMALL_SHOP', 20);
