insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Bauch-Ernser', 267, 'SMALL_SHOP', 1);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Pollich, Waelchi and Gutmann', 840, 'SHOP', 2);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Dooley, Kutch and Carter', 191, 'SMALL_SHOP', 3);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Waters Group', 708, 'SHOP', 4);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Schulist Inc', 74, 'SHOP', 5);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Emard, Olson and Mueller', 946, 'SMALL_SHOP', 6);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Harber, Hilll and Schmidt', 394, 'SMALL_SHOP', 7);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Mosciski Inc', 196, 'SHOP', 8);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Conroy, Kohler and Farrell', 420, 'SMALL_SHOP', 9);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Stroman and Sons', 996, 'SHOP', 10);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Goodwin Group', 102, 'SMALL_SHOP', 11);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Leannon, Reinger and Crona', 730, 'SMALL_SHOP', 12);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Kuhn LLC', 305, 'SMALL_SHOP', 13);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Lindgren-Howell', 535, 'SMALL_SHOP', 14);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Cartwright LLC', 333, 'SMALL_SHOP', 15);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Heller, Bailey and Waelchi', 92, 'SMALL_SHOP', 16);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Leffler, Abshire and Leannon', 749, 'SHOP', 17);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Robel Inc', 744, 'SHOP', 18);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Schoen-Bayer', 553, 'SMALL_SHOP', 19);
insert into SIDLO (jmeno, plocha, typ_sidla, adresa) values ('Klein Inc', 216, 'SMALL_SHOP', 20);
